---
- name: Verify web server
  hosts: all
  tasks:
    - name: Wait for the web server to start
      ansible.builtin.wait_for:
        port: 8989
        delay: 10
        timeout: 30

    - name: Verify that the web server is serving content
      ansible.builtin.uri:
        url: http://localhost:8989
        return_content: true
      register: web_content

    - name: Verify that the web server is serving content
      ansible.builtin.uri:
        url: http://localhost:8989/ping
        return_content: true
      register: ping_endpoint

    - name: Check if the web server is up
      ansible.builtin.assert:
        that:
          - "'<title>Sonarr</title>' in web_content.content"
          - "'\"status\": \"OK\"' in ping_endpoint.content"
